# Generated by Django 2.1 on 2018-08-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(default='imagens/none/no-img.jpg', upload_to='imagens/livros/', verbose_name='Imagen da capa')),
                ('titulo', models.CharField(max_length=40, verbose_name='Nome')),
                ('genero', models.CharField(max_length=100, verbose_name='Genero')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('editora', models.CharField(max_length=50, verbose_name='Editora')),
                ('paginas', models.IntegerField(verbose_name='Número de páginas')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LER', 'Ler'), ('LENDO', 'Lendo'), ('LIDO', 'Lido')], default='LER', max_length=15)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='books.Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'userbook',
                'verbose_name_plural': 'usersbooks',
            },
        ),
    ]
